### ISSUE TITLE
some 'top sites' don't seem to work yet.

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-http2#100]
tested with swift-nio-http2 commit 492f375a14067457636b7eec8226436b580f477e and the http2-client from swift-nio-examples. Note, these might be bugs in http2-client too, I know it doesn't race the connections properly which might be the source of the hangs.

- `ERROR: InvalidStreamIDForPeer()`:
  - ~https://amazon.com~ (ALPN fails, http2-client doesn't check)
  - ~https://vimeo.com~ (ALPN fails, http2-client doesn't check)
  - ~https://bit.ly~ (ALPN fails, http2-client doesn't check)
  - ~https://baidu.com~ (ALPN fails, http2-client doesn't check)
  - ~https://github.com~ (ALPN fails, http2-client doesn't check)
  - ~https://soundcloud.com~ (ALPN fails, http2-client doesn't check)
  - ~https://paypal.com~ (ALPN fails, http2-client doesn't check)
  - ~https://imdb.com~ (ALPN fails, http2-client doesn't check)
- `ERROR: uncleanShutdown`:
  - ~https://microsoft.com/~ (Regular TLS error, http2-client should suppress)
  - ~https://weebly.com~ (Regular TLS error, http2-client should suppress)
- hangs:
  - ~https://godaddy.com~ (ALPN fails, http2-client doesn't check)
  - https://yahoo.com
  - https://qq.com
  - ~https://huffingtonpost.com~ (ALPN fails, http2-client doesn't check)
- `ERROR: handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268436576 error:10000460:SSL routines:OPENSSL_internal:reason(1120)]))` (unlikely to be h2 related)
  - ~https://ebay.com~ (ALPN fails and eBay, unlike basically all other implementations, sends back a fatal error instead of completing the handshake)

```
curl https://moz.com/top500/domains/csv  | cut -d, -f2 | tr -d '"' | while read site; do if curl --http2-prior-knowledge -s "https://$site" > /dev/null; then echo $site; ./.build/x86_64-apple-macosx/debug/http2-client "https://$site" > /dev/null || echo "BAD $site"; fi; done
```

**Comment by Lukasa** [comment]
`uncleanShutdown` is not interesting: this is a regular TLS error message that means that Microsoft did not send `CLOSE_NOTIFY`, and can be suppressed in http2-client.

**Comment by weissi** [comment]
> `uncleanShutdown` is not interesting: this is a regular TLS error message that means that Microsoft did not send `CLOSE_NOTIFY`, and can be suppressed in http2-client.

Agreed, probably we should ignore (if content-length has been matched) in http2-client

**Comment by Lukasa** [comment]
So the `InvalidStreamIDForPeer` errors are masking the actual issue for those sites, let me try to clean that up a bit.

**Comment by Lukasa** [comment]
Ok, at least *some* of these are actually swift-nio-http2 bugs. Specifically, swift-nio-http2 does not check the return value of the ALPN negotiation, which means it speaks HTTP/2 to some servers that do not speak HTTP/2 back. In particular, this is what Amazon is doing: ALPN is not negotiated, and so the `InvalidStreamIDForPeer` is masking a `FrameSizeError` that comes from attempting to interpret the HTTP/1.1 response as a HTTP/2 response.

While we could have better heuristics here, the error is not unreasonable.

**Comment by Lukasa** [comment]
So, as a first instance, http2-client should probably use the ALPN handler in `NIOTLS`.

**Comment by Lukasa** [comment]
Ok, all the `InvalidStreamIDForPeer` errors are actually ALPN failures.

**Comment by Lukasa** [comment]
Filed apple/swift-nio-examples#12 and apple/swift-nio-examples#13.

**Comment by Lukasa** [comment]
@weissi Can you try testing yahoo.com again? When I run against yahoo.com I get a 301 redirect with the body text "redirect". (Incidentally they also send RST_STREAM *twice* after they send their END_STREAM frame, but that isn't an error and nio-http2 doesn't report it as one.

**Comment by Lukasa** [comment]
On my machine qq.com has a connection timeout, unrelated to swift-nio-http2.
