### ISSUE TITLE
Proposed change to BadStreamStateTransition for debuggability

### ISSUE THREAD

**Issue by nealsid** [apple/swift-nio-http2#151]
I'm just beginning to dig into the HTTP/2 and Swift-NIO code and wanted to get some feedback on a proposal to modify BadStreamStateTransition to have from/to states to improve debuggability when it gets logged (and maybe in the future, stack traces when it gets created)

A few questions:

- The HTTP2StateMachine.State enum is private, and comments indicate that it's so people don't erroneously set the state directly.  Isn't the right place to do this in setting the member state variable to private (which it already is)?   If that works I could make it internal and move the state enum outside of HTTP2StateMachine

- I'm seeing some comments that (to me) don't agree with the RFC. I am no HTTP expert by any means and I'm fairly new to Swift, as well, so I wouldn't be surprised if I"m wrong here, but on line 379, it indicates sending HEADERS on an idle stream isn't permitted, but the state transition diagram and the RFC both seem to indicate that it should transition a stream to open.  

Apologies for the basic questions, like I mentioned I'm new. Thanks in advance for your help.

Neal

**Comment by Lukasa** [comment]
This seems like a good idea, I’m in favour of it! In answer to your questions:

> The HTTP2StateMachine.State enum is private, and comments indicate that it's so people don't erroneously set the state directly. Isn't the right place to do this in setting the member state variable to private (which it already is)?

At the time there was no good reason to expose the type to other parts of the code. You have found one, so the status quo should change. By all means change the visibility. Please leave it nested inside the state machine type though; we don’t gain anything by hoisting it out, and it helps avoid the type seeming to be generally useful. 

> on line 379, it indicates sending HEADERS on an idle stream isn't permitted, but the state transition diagram and the RFC both seem to indicate that it should transition a stream to open.

A server is not permitted to send a HEADERS frame on an idle stream. RFC 7540 does say this, just not in the connection state machine diagram. 

If you read the comment in the code next to our reproduction of the state machine diagram you’ll notice that it says that the RFC 7540 diagram is so incomplete as to be actively misleading. In this case, our (much more detailed) state machine is right: RFC 7540’s diagram is wrong.

**Comment by Lukasa** [comment]
> One scenario that I was thinking about was exposing ]information about the streams in a server built off this code. If someone wants to drill down into the various open streams by connection state, is it possible to select all, say, .idle streams independent of the associated data?

I am not sure that this is something anyone is actually going to do, so I don’t think I’d worry too much about the feature: in general we don’t let users do too much introspection of this state. 

For the Comparable issue, the best solution may be to implement a parallel enum without associated data expressly for debugging purposes, and make that more visible.

**Comment by nealsid** [comment]
Didn't get the chance today because of a long drive, but I agree that end users of apps providers by the server would not need to introspect the state, but I think someone in a DevInfra role or anyone required to monitor the servers need information like that.  It may be worth considering either:

- Considering alternatives to associated data for each stream state (but the way I am familiar with, by having a bunch of member variables, a subset of which are used for each state, is not very elegant)

- Maybe it's wishful thinking, but maybe being able to compare Swift enums independent of associated data is on the language roadmap. Seems like enough people have run into this for it to be useful

Duplicating the enum seems like it'd be a maintainability tax in the long term.  I'm happy to prototype it just to see while we iterate on what the final solution looks like.

Thanks!

**Comment by Lukasa** [comment]
We should separate the requirement to _see_ the state from the requirement to be able to operate upon the state. If our goal is to allow users only to see the state, that can be achieved by exposing the enum, without adding any `Comparable` requirement. The only reason I can see to provide an implementation of `Comparable` is to allow reasoning about the state, and I’m not even entirely sure what utility that would provide.

Can you outline why we end up with a requirement to implement `Comparable`?

**Comment by nealsid** [comment]
@Lukasa: If you look at the code, BadStreamStateTransition conforms to NIOHTTP2Error.  Once I add the to/from states as members to BadStreamStateTransition, it is no longer comparable because one of teh types that is associated data of HTTP2StreamStateMachine.State values is not comparable.  I did not have the time to find out which.

I don't know if that makes sense, or not?

**Comment by Lukasa** [comment]
NIOHTTP2Error shouldn’t require Comparable, only Equatable.
