### ISSUE TITLE
HTTP2to1ServerCodec: should we be more tolerant with the headers the user provides

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-http2#152]
- we should probably lower-case the header names automatically
- we should probably just ignore `connection: keep-alive/close`
- we should probably drop `transfer-encoding: chunked`

**Comment by weissi** [comment]
CC @Lukasa for input

**Comment by Lukasa** [comment]
We should chat to some of the community folks about this; Tanner asked about some of these restrictions in the past and expressed an interest in us leaving them there rather than making all users pay the cost of rationalising the headers.

**Comment by weissi** [comment]
I see, we could make it configurable? Because I think the default behaviour should 'just work'. And it's odd that the users currently need to lower-case manually...

CC @tanner0101

**Comment by Lukasa** [comment]
I’m fine with changing the behaviour and making it configurable.
