### ISSUE TITLE
Provide helper pipeline constructor for mixed-protocol HTTP/1 and HTTP/2 servers

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-http2#186]
A very common use-case is to have a "HTTP Server" that wants to be able to speak both HTTP/1 and HTTP/2. This server will use ALPN to negotiate which HTTP protocol it speaks as part of the TLS handshake, and then configure the pipeline dynamically using the [`ApplicationProtocolNegotiationHandler`](https://apple.github.io/swift-nio/docs/current/NIOTLS/Classes/ApplicationProtocolNegotiationHandler.html). To make users's lives easier, they will almost certainly use the [`HTTP2ToHTTP1ServerCodec`](https://apple.github.io/swift-nio-http2/docs/current/NIOHTTP2/Classes/HTTP2ToHTTP1ServerCodec.html) to bridge the abstraction boundary, and then have a "common" HTTP pipeline that is inserted either into every HTTP/1 channel or to every HTTP/2 stream channel.

While this is a very common pattern, the `ApplicationProtocolNegotiationHandler` is written to solve a very general version of this problem. This means every implementer is forced to write a lot of code that is basically _always_ identical:

1. Check the ALPN negotiation, defaulting `nil` to `"http/1.1"`.
2. Configure the normal parts of the HTTP pipeline
3. Add their handlers as needed

This duplication is a bit sad, especially as there's only really one correct implementation.

We can help here by adding a `Channel.configureMultiProtocolHTTPServer` function. This function would handle the common parts of that setup: adding an `ApplicationProtocolNegotiationHandler` that can handle both `"h2"` and `"http/1.1"` protocols, that knows how to do the fallback, and that knows how to configure the HTTP pipelines for the basic use-cases.

In the HTTP/1.1 case, it'll call `ChannelPipeline.configureHTTPServerPipeline`, putting in all the appropriate handler types, and then calling the user-provided initializer. In the HTTP/2 case it'll call `Channel.configureHTTP2ServerPipeline`, and provide a stream channel initializer that inserts the `HTTP2ToHTTP1ServerCodec` handler and then calls the user-provided initializer.

The signature should be:

```swift
extension Channel {
    func configureMultiProtocolHTTPServer(_ channelInitializer: @escaping (Channel) -> EventLoopFuture<Void>) -> EventLoopFuture<Void>
}
```

This would be of real value to folks like @tanner0101 if they want to add HTTP/2 server support, as they should be able to abstract away essentially all of the boilerplate. A chunk of similar code [exists in grpc-swift](https://github.com/grpc/grpc-swift/blob/e3ab183d95a2ee77929240e23b119426d581c821/Sources/GRPC/HTTPProtocolSwitcher.swift#L121-L141).

**Comment by weissi** [comment]
CC @csloan

**Comment by Lukasa** [comment]
This is done.
