### ISSUE TITLE
newly opened child channels receive `channelActive` before the parent channel

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-http2#26]
creating a child channel in the `childChannelInitializer`

```swift
        func requestStreamInitializer(channel: Channel, streamID: HTTP2StreamID) -> EventLoopFuture<Void> {
            return channel.pipeline.addHandlers([HTTP2ToHTTP1ClientCodec(streamID: streamID, httpProtocol: .https),
                                                 SendAGETRequestHandler(responseReceivedPromise: self.responseReceivedPromise)],
                                                first: false)
        }

        self.multiplexer.createStreamChannel(promise: nil, requestStreamInitializer)
```

will have `SendAGETRequestHandler` see `channelActive` when `ctx.channel.parent!.isActive` is still `false`. That's a problem because when sending a request in the child's `channelActive` the program will crash as the HTTP2Parser's `session: NGHTTP2Session!` is still `nil`, ie. we'll crash.

**Comment by MrMage** [comment]
Does this mean that trying to use an HTTP2 client based on this library would always fail right now, or does this only affect some special case? (I'm not in a hurry, just curious.)

**Comment by weissi** [comment]
> Does this mean that trying to use an HTTP2 client based on this library would always fail right now, or does this only affect some special case? (I'm not in a hurry, just curious.)

This does mean that if you fire off a request in the child channel in its initialiser/channelActive, you'll crash. You'll need to wait for both the parent & the child channel to receive `channelActive`. That's why in https://github.com/apple/swift-nio-examples/pull/6 I have`CreateRequestStreamHandler` which opens the new stream (aka the child channel) only when the parent channel receives `channelActive`.

**Comment by Lukasa** [comment]
Yup, good catch: that just calls `activate` way too early.
