### ISSUE TITLE
Update CI for NIO 2.0 cycle.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-http2#31]
I've just branched `nghttp2-support-branch`, so we can begin moving forward for the NIO 2.0 release cycle by updating the CI on this repository.

@tomerd, can we change the CI setup so that the `master` branch has only got a Swift 5.0 builder (for both the branch and PRs), and the `nghttp2-support-branch` has a Swift 4.1 and Swift 4.2 builder?

**Comment by tomerd** [comment]
@Lukasa once https://github.com/apple/swift-nio-http2/pull/33 is merged i can do the jenkins part

**Comment by Lukasa** [comment]
Fantastic, #33 is merged.

**Comment by weissi** [comment]
this is done fortunately :)
