### ISSUE TITLE
Failed assertion in change from 1.24.1 to 1.25.0

### ISSUE THREAD

**Issue by pardeike** [apple/swift-nio-http2#375]
We experience an assertion failure in our gRPC client in this assertion:

https://github.com/apple/swift-nio-http2/compare/1.24.1...1.25.0#diff-cf9025d8ea6d311afe1a3ad83fd8c3456c162d86fde91c690e081490f0ec99f3R841

We use grpc-swift 1.14.1

**Comment by Lukasa** [comment]
Can you provide the text of that assertion please?

**Comment by pardeike** [comment]
The problem appears in our app we deploy in production of the Swedish Police. So no, right now I cannot give you more details. The problem appeared a few days ago for the first time (grpc-swift unfortunately uses “from:” and it’s a sporadic problem. 

Our tester has produced it once and now that I know you’re interested I can ask him to reproduce and get what you asked for. I do have these screenshots I am allowed to share. Sorry for the limiting crop:

![5E5E1D85-5175-4D84-9B83-5659C950D2EA](https://user-images.githubusercontent.com/853584/222205357-382b8c37-0e8c-4646-97d2-ea6d5ad5862c.jpeg)
![119BB197-9A24-4E3C-A89E-F0192D960934](https://user-images.githubusercontent.com/853584/222205370-7f845e95-d030-4b71-8ef8-e21a0f271d7a.jpeg)

**Comment by Lukasa** [comment]
I'll take a look. Separately, if this is crashing in production I'm a bit worried: the `assert` in question should not crash in a release build but should produce a runtime error. Is there a reason your production app isn't being shipped in release mode?

**Comment by Lukasa** [comment]
Fixed in 1.25.2.
