### ISSUE TITLE
Closing a stream immediately after creating it causes a fatal error

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio-http2#39]
`close()`-ing a newly created stream channel causes a fatal error because a `nil` optional (`networkStreamID`) is forcibly unwrapped [here](https://github.com/apple/swift-nio-http2/blob/f1d875433faf63f733f614b0c5e5bd1a90677b7d/Sources/NIOHTTP2/NGHTTP2Session.swift#L822). 

The documentation for `networkStreamID` says it will be `nil` if "the stream has not yet reached the network".

Closing a stream prior to it reaching the network seems like valid behaviour, albeit an edge case, which shouldn't cause a fatal error.

**Comment by Lukasa** [comment]
Agreed. Conveniently, this should be easily fixed.

**Comment by Lukasa** [comment]
No longer relevant.
