### ISSUE TITLE
Support close mode when closing HTTP2StreamChannel

### ISSUE THREAD

**Issue by gjcairo** [apple/swift-nio-http2#437]
Right now, the `close0` implementation of `HTTP2StreamChannel` doesn't do anything with the close mode: [link](https://github.com/apple/swift-nio-http2/blob/a0c580be160af313d1d7d3bf5dda874b9abd025b/Sources/NIOHTTP2/HTTP2StreamChannel.swift#L583).
We should add support for the different close modes.

**Comment by glbrntt** [comment]
I think we looked at our problem the wrong way. The problem being how to close only the inbound stream when using `NIOAsyncChannel`. At the moment it closes it on `channelInactive`, `channelError` and on the `ChannelEvent.inputClosed` user inbound event. 

The first two aren't appropriate so and we made the mistake of thinking "we need `ChannelEvent.inputClosed` so we need `close0` to support close modes". I think we can just fire the user inbound event when we receive a frame with the end stream flag set, which I think makes sense in this situation.
