### ISSUE TITLE
Stream Closed

### ISSUE THREAD

**Issue by jugu1991** [apple/swift-nio-http2#460]
hi, i use Vapor for a network  request, but always receive error:

<pre>
 StreamClosed(streamID: HTTP2StreamID(20003), errorCode: HTTP2ErrorCode<0x8 Cancel>, location: "NIOHTTP2/HTTP2StreamChannel.swift:881"),desc: The operation could not be completed. (NIOHTTP2.NIOHTTP2Errors.StreamClosed error 1.),

</pre>

<pre>
HTTPClientError.cancelled,desc: The operation could not be completed. (AsyncHTTPClient.HTTPClientError error 1.)
</pre>

**Comment by Lukasa** [comment]
The stream has likely been closed from the network side. This can be a GOAWAY frame, or a number of other possible HTTP/2 frames. Do you have a reproducer scenario for this?

**Comment by jugu1991** [comment]
> The stream has likely been closed from the network side. This can be a GOAWAY frame, or a number of other possible HTTP/2 frames. Do you have a reproducer scenario for this?

request url: https://fapi.binance.com/fapi/v1/continuousKlines?interval=15m&contractType=PERPETUAL&pair=WLDUSDT&limit=96

This is not a guaranteed occurrence, but I've encountered it in a Vapor project. In my project, it's possible that multiple concurrent requests are sent to this URL, and so far, it may happen several times a day.

**Comment by jugu1991** [comment]
> The stream has likely been closed from the network side. This can be a GOAWAY frame, or a number of other possible HTTP/2 frames. Do you have a reproducer scenario for this?

@Lukasa

 request url: https://fapi.binance.com/fapi/v1/continuousKlines?interval=15m&contractType=PERPETUAL&pair=WLDUSDT&limit=96

This is not a guaranteed occurrence, but I've encountered it in a Vapor project. In my project, it's possible that multiple concurrent requests are sent to this URL, and so far, it may happen several times a day.

**Comment by Lukasa** [comment]
Ah, frequently this is an artifact of loadbalancers like nginx, which set a cap on the maximum number of streams they will allow before they terminate the connection. Try using the configuration setting [`maximumUsesPerConnection`](https://github.com/swift-server/async-http-client/blob/11205411bb60612f0a1a04f733fa71b4fb864ab9/Sources/AsyncHTTPClient/HTTPClient.swift#L733) and setting it to below 10,000 and see if the issue goes away.

**Comment by jugu1991** [comment]
> Ah, frequently this is an artifact of loadbalancers like nginx, which set a cap on the maximum number of streams they will allow before they terminate the connection. Try using the configuration setting [`maximumUsesPerConnection`](https://github.com/swift-server/async-http-client/blob/11205411bb60612f0a1a04f733fa71b4fb864ab9/Sources/AsyncHTTPClient/HTTPClient.swift#L733) and setting it to below 10,000 and see if the issue goes away.

@Lukasa After following your setting of maximumUsesPerConnection=10000, no errors are reported so far. It seems to be resolved. Thank you.
