### ISSUE TITLE
Bad Package.swift file

### ISSUE THREAD

**Issue by ggilley** [apple/swift-nio-http2#467]
This Package.swift file has dependencies with missing .git extensions. It's causing xcode to lose its mind when I try to update my package which indirectly depends on this package:

        .package(url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0"),

**Comment by Lukasa** [comment]
We can just drop that extension altogether shortly, when we roll out the Github actions pieces.

Separately, have you filed a Feedback assistant report for the Xcode issue? It'd be helpful to have a bug report to point the Xcode team at, as this should be fine.

**Comment by glbrntt** [comment]
Closing as this dependency has been removed the package manifest.
