### ISSUE TITLE
handling connection-specific header fields

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio-http2#47]
According to RFC 7540 ([§ 8.1.2.2](https://tools.ietf.org/html/rfc7540#section-8.1.2.2)):

> An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed

Currently, `NIOHTTP2` allows fields like `Connection` to be serialized. These fields should either be:

1. Stripped from the response.
2. Result in a serialization error. 

I personally prefer (2) slightly since I'd rather remove these headers myself if I have to than be wasting CPU time adding them only to have them silently removed.

**Comment by Lukasa** [comment]
No longer relevant in swift-nio-http2 1.0: these fields now trigger an error.
