### ISSUE TITLE
Zero length data frames are not correctly parsed

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio-http2#49]
Zero length data frames aren't parsed correctly in HTTP2FrameParser.swift:
 
https://github.com/apple/swift-nio-http2/blob/0ac9fa6e30c4283902277ce3d6e5a2a2f1b05879/Sources/NIOHTTP2/HTTP2FrameParser.swift#L408

**Comment by Lukasa** [comment]
Fixed in #51.
