### ISSUE TITLE
why is configureHTTP2Pipeline on Channel and not ChannelPipeline

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-http2#73]
usually the `configure*` methods are on the `ChannelPipeline`. For some reason, `configureHTTP2Pipeline` is an extension on `Channel` rather than `ChannelPipeline`. Any particular reason or just an oversight?

**Comment by Lukasa** [comment]
Yes: the multiplexer needs access to the parent Channel in its constructor, so putting it on the pipeline doesn’t work.

**Comment by normanmaurer** [comment]
maybe I am missing something but couldn't we just call `self.channel.parent` ?

**Comment by Lukasa** [comment]
This is for the stream multiplexer which lives on the parent channel. The question is how the stream multiplexer gets its `self.channel`. It either waits until `handlerAdded`, which requires making `self.channel` optional, or force users to provide it on `init`. I tried out the second one.
