### ISSUE TITLE
Max frame size can be (1<<24)-1

### ISSUE THREAD

**Issue by guoye-zhang** [apple/swift-nio-http2#96]
In `validateSettings()` (ConnectionStateMachine.swift:1311)
```
            case .maxFrameSize:
                guard setting._value >= (1 << 14) && setting._value < ((1 << 24) - 1) else {
```

However, `(1 << 24) - 1` is a valid frame size. The comparison should be `setting._value < (1 << 24)`

**Comment by Lukasa** [comment]
Yup, that's a classic off-by-one error. Thanks for reporting!
